services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=ASDasd123
      - POSTGRES_DB=mypostgresdb
    volumes:
      - turboPostgresVolume:/var/lib/turboPostgresVolume

  http:
    container_name: httpContainer
    ports:
      - 3001:3001
    build:
      context: ./
      network: host
      dockerfile: ./docker/Dockerfile.http
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres

  ws:
    container_name: wsContainer
    ports:
      - 8080:8080
    build:
      context: ./
      network: host
      dockerfile: ./docker/Dockerfile.ws
    depends_on:
      - postgres

  web:
    container_name: webContainer
    ports: -3000:3000
    build:
      context: ./
      dockerfile: /docker/Dockerfile.frontend
      environment:
        - DATABASE_URL="postgresql://postgres:ASDasd123@localhost:5432/mypostgresdb"
    depends_on:
      - postgres

volume:
  - turboPostgresVolume:
