FROM node:18-alpine

WORKDIR /usr/src

ARG POSTGRES_CONNECTION_URL

COPY ./package*.json ./

COPY ./packages ./packages

COPY ./turbo.json ./turbo.json

COPY ./apps/web ./web

RUN npm install
RUN npm run db:generate
RUN DATABASE_URL=${DATABASE_URL} npm run build

EXPOSE 3000

CMD [ "npm", "start:ws" ]